#pragma once
#include <list>
#include <string>
#include <projectX/math.h>
#include <projectX/tools/textmanipulation.cpp>
#include <projectX/tools/rangeloop.cpp>
#include <projectX/sysout.h>
#include <projectX/logging/log.cpp>
#include <projectX/constants/sizes.cpp>
#include <projectX/constants/ranges.cpp>
#include <projectX/tools/arrays.cpp>
#include <projectX/initcontrol/initcontrol.cpp>